### PR TITLE
Implement https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/issues/94

### PR DESCRIPTION
**Pull request by Silvertower**
Move Auxiliary Actions to the end of strike groups, as they are more dynamic and less used than other actions (such rolling a strike, damage, and toggling versatile, etc).

### CODE REVIEW

**Comment by Silvertower** [comment]
I guess I don't know how Git works, so even though I made multiple branches, they appear to be "accumulating" in my pull requests. Not sure how to fix.

**Comment by Larkinabout** [comment]
> I guess I don't know how Git works, so even though I made multiple branches, they appear to be "accumulating" in my pull requests. Not sure how to fix.

I just need to accept and merge them on my side. Let me know when you feel like you've come to a head with your developments and I'll push out a release. You seem to have quickly become comfortable with the developments, so if you do decide you'd like to take it over, let me know.

**Comment by Silvertower** [comment]
I guess I could try taking over in an interim role and see how it goes. I'm not sure how that works on the GitHub/Foundry module side, as I am not overly familiar with GitHub or how modules are registered with Foundry's module browser, etc. My knowledge of git in general is very limited, as I am not a developer by trade.

**Comment by Larkinabout** [comment]
It's mostly just the GitHub release process and then listing on Foundry side of things. I'll see if I can give you access to create releases on this repos, so you can get comfortable with that side of it. It's mostly automated through the Release Creation workflow action, so all you really need to do it draft a new release, give it a tag (which is also the version number), fill out the release notes and then publish the release.

The listing on Foundry can only be done by the owner. Ownership can be transferred but I expect Foundry wouldn't want to change it back and forth, so I'd treat it as a semi-permanent change. Until and unless you're happy to say you'll take it over for the foreseeable future, we'll just leave that bit in my hands and you can let me know when you have a release ready for listing.

**Pull request merged**
